### ISSUE TITLE
Open or Search triggers a Form Submit

### ISSUE THREAD

**Issue by gmisa** [Jimdo/angular-fontselect#48]
Hi, im not sure if this is by design, but each time i click on Search or Open, the form submits.  How do I prevent that behavior?

Thanks

**Comment by Xiphe** [comment]
i guess, that's not by design but because we have not jet used this in a `<form>` element and the search and open actions are triggered by a button that has no `preventDefault`. I'll look into that later

**Comment by Xiphe** [comment]
though, i'm not sure if any good values will be submitted with the form :confused:

**Comment by Xiphe** [comment]
should be fixed with [v0.12.4](https://github.com/Jimdo/angular-fontselect/releases/tag/v0.12.4)
