### ISSUE TITLE
Create list headlines

### ISSUE THREAD

**Issue by KarstenBuckstegge** [Jimdo/angular-fontselect#50]
Popular fonts and all fonts should have non-clickable headline blocks.

**Comment by KarstenBuckstegge** [comment]
![](https://cloud.githubusercontent.com/assets/2949718/13050347/0b41d5d4-d3f3-11e5-9b52-c4771fda2ca2.png)

**Comment by Xiphe** [comment]
done with 4f34b4784606ca014dcdd5d7379e38fea97af49c
