### ISSUE TITLE
Some font load just their name letters

### ISSUE THREAD

**Issue by barbax** [Jimdo/angular-fontselect#58]
Hello!

There is a really weird problem here!

After implementing the library a strange thing start happening.
Some fonts doesn't load well. In some cases this fonts just load the letters in their name. In the screenshoot below you can see an example 

<img width="707" alt="schermata 2017-01-19 alle 20 32 41" src="https://cloud.githubusercontent.com/assets/3686977/22122048/a391d5fc-de86-11e6-9698-a9e3056c06c4.png">

Looking the console this is the file loaded:
http://fonts.googleapis.com/css?family=Fjalla+One:regular&text=Fjalla%20One 
with this content:
`@font-face {
  font-family: 'Fjalla One';
  font-style: normal;
  font-weight: 400;
  src: local('Fjalla One'), local('FjallaOne-Regular'), url(http://fonts.gstatic.com/l/font?kit=ZRI0JPgrEnSFSbERuWus_Zuu-THSsfPN_lAN0B
DN6tU&skey=81738d23c31d6227&v=v4) format('woff2');
}
`

This is the file returned: [font (3).woff2.zip](https://github.com/Jimdo/angular-fontselect/files/717589/font.3.woff2.zip)

If i convert this woff2 in ttf (to see it on my mac) i just see the letters of the name. 

Thanks!

**Comment by Xiphe** [comment]
For performance reasons, only the letters of the font-name are loaded for the preview, when browsing through the list. 

If you then select a specific font, the whole set should be loaded.

Though i'm not longer a maintainer of this project, the [demo page](http://jimdo.github.io/angular-fontselect/) still seems to work as expected, maybe you can check the implementation there and find if something on your side is wrong.

**Comment by barbax** [comment]
right,it makes sense.
 Do you know if there is a way to force loading of the whole set, or to fire the "font selected" event?

Thanx

**Comment by Xiphe** [comment]
the [`current` and `stack` attributes of the jdFontselect directive](https://github.com/Jimdo/angular-fontselect/blob/master/src/js/directive.fontselect.js#L9-L10) should be two-way-bindable

**Comment by daniel42na** [comment]
You can force loading whole set of font characters. Just remove **[text: font.name](https://github.com/Jimdo/angular-fontselect/blob/ab383624c25e81ba6f4f097c90412bae89b36eca/src/js/service.fonts.js#L677)**  from **_loadGoogleFont** function ;)

**Comment by tony-tran** [comment]
Hi @barbax,

I have exactly the same issue of you. Have you resolve your problem? If yes, how ? Thank you in advance.

**Comment by barbax** [comment]
Hello @tony-tran . Unfortunately not. 
We just implemented ourselves a similar solution. It has been faster than try to fix this. 

Sorry

**Comment by Xiphe** [comment]
thank for the feedback :)
